"""baseline_slice_schema

Revision ID: 53471dfb1b46
Revises: 
Create Date: 2026-05-15 17:48:45.867081+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53471dfb1b46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('actor_role', sa.String(length=64), nullable=False),
    sa.Column('actor_label', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('engagement_id', sa.String(length=36), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('target_kind', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_engagement_id'), ['engagement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_run_id'), ['run_id'], unique=False)

    op.create_table('customer',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_slug'), ['slug'], unique=True)

    op.create_table('engagement',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagement_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_slug'), ['slug'], unique=False)

    op.create_table('identity',
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_kind', sa.String(length=32), nullable=False),
    sa.Column('canonical_label', sa.String(length=255), nullable=False),
    sa.Column('sid', sa.String(length=184), nullable=True),
    sa.Column('upn', sa.String(length=320), nullable=True),
    sa.Column('sam_account_name', sa.String(length=255), nullable=True),
    sa.Column('object_guid', sa.String(length=36), nullable=True),
    sa.Column('azure_object_id', sa.String(length=36), nullable=True),
    sa.Column('is_privileged', sa.Boolean(), nullable=False),
    sa.Column('is_tier0', sa.Boolean(), nullable=False),
    sa.Column('is_breakglass', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_azure_object_id'), ['azure_object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_object_guid'), ['object_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_sid'), ['sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_upn'), ['upn'], unique=False)

    op.create_table('assessment_run',
    sa.Column('engagement_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_run_engagement_id'), ['engagement_id'], unique=False)

    op.create_table('evidence',
    sa.Column('assessment_run_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_type', sa.String(length=128), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_run_id'], ['assessment_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_assessment_run_id'), ['assessment_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_module_id'), ['module_id'], unique=False)

    op.create_table('finding',
    sa.Column('assessment_run_id', sa.String(length=36), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('license_status', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('customer_visibility', sa.String(length=32), nullable=False),
    sa.Column('summary_internal', sa.Text(), nullable=False),
    sa.Column('summary_customer', sa.Text(), nullable=True),
    sa.Column('technical_detail', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('identity_refs', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_run_id'], ['assessment_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_assessment_run_id'), ['assessment_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_customer_visibility'), ['customer_visibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_state'))
        batch_op.drop_index(batch_op.f('ix_finding_severity'))
        batch_op.drop_index(batch_op.f('ix_finding_module_id'))
        batch_op.drop_index(batch_op.f('ix_finding_customer_visibility'))
        batch_op.drop_index(batch_op.f('ix_finding_category'))
        batch_op.drop_index(batch_op.f('ix_finding_assessment_run_id'))

    op.drop_table('finding')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_module_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_assessment_run_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('assessment_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_run_engagement_id'))

    op.drop_table('assessment_run')
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_upn'))
        batch_op.drop_index(batch_op.f('ix_identity_sid'))
        batch_op.drop_index(batch_op.f('ix_identity_object_guid'))
        batch_op.drop_index(batch_op.f('ix_identity_customer_id'))
        batch_op.drop_index(batch_op.f('ix_identity_azure_object_id'))

    op.drop_table('identity')
    with op.batch_alter_table('engagement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagement_slug'))
        batch_op.drop_index(batch_op.f('ix_engagement_customer_id'))

    op.drop_table('engagement')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_slug'))

    op.drop_table('customer')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_run_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_event_engagement_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_customer_id'))

    op.drop_table('audit_event')
    # ### end Alembic commands ###
