"""SQLAlchemy engine, session factory, and Base.

POC V1 uses SQLite by default (D-0024 — temporary while Postgres is blocked on
WSL Virtual Machine Platform). Switching to Postgres only requires changing
`DATABASE_URL`; no application-code change is needed because:
  - SQLAlchemy 2.x targets both engines from the same model definitions.
  - JSON columns use the portable `sqlalchemy.JSON` type (maps to JSONB on
    Postgres, TEXT on SQLite).
  - UUIDs are generated by Python, not by the database.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any

from sqlalchemy import create_engine
from sqlalchemy.engine import Engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from platform_core.settings import get_settings


class Base(DeclarativeBase):
    """Single declarative base for all platform_core + module SQLAlchemy models."""


_engine: Engine | None = None
_SessionLocal: sessionmaker[Session] | None = None


def _build_engine() -> Engine:
    settings = get_settings()
    connect_args: dict[str, Any] = {}
    if settings.database_url.startswith("sqlite"):
        # FastAPI's threadpool issues require this for SQLite. POC V1 only.
        connect_args["check_same_thread"] = False
        # Ensure the SQLite parent directory exists so the file can be created.
        url_path = settings.database_url.split("///", 1)[-1]
        if url_path and url_path != ":memory:":
            from pathlib import Path

            Path(url_path).parent.mkdir(parents=True, exist_ok=True)
    return create_engine(settings.database_url, connect_args=connect_args, future=True)


def get_engine() -> Engine:
    global _engine
    if _engine is None:
        _engine = _build_engine()
    return _engine


def _session_factory() -> sessionmaker[Session]:
    global _SessionLocal
    if _SessionLocal is None:
        _SessionLocal = sessionmaker(
            bind=get_engine(), autoflush=False, autocommit=False, future=True
        )
    return _SessionLocal


def get_db() -> Iterator[Session]:
    """FastAPI dependency: yields a session, closes it on exit."""
    session = _session_factory()()
    try:
        yield session
    finally:
        session.close()


def reset_for_tests() -> None:
    """Drop the cached engine/session — used by tests that swap DATABASE_URL."""
    global _engine, _SessionLocal
    _engine = None
    _SessionLocal = None
